package com.dreamxi.app.sim

import kotlin.random.Random

// GENERATED by etl/goal_minutes.py from real World Cup goal minutes. Do not edit by hand.

/**
 * When a goal is scored inside the ninety.
 *
 * Every minute used to be equally likely, which was the honest choice while
 * no data in the app recorded one. The World Cup scrape brought back
 * 1,084 real goal minutes off Wikipedia, so this is measured now.
 *
 * TWO EFFECTS, FITTED SEPARATELY:
 *
 *  - an in-play tilt, rate = 8.438 + 0.0514 x minute, fitted on the
 *    963 goals in open play, so the closing quarter-hour is worth about
 *    1.4x the opening one;
 *  - stoppage time, 121 goals (11.2%), recorded at the 45th and 90th
 *    minute where the scoresheets put it. Those two minutes are not fitted at
 *    all -- they carry exactly what was scored in them, 9.8% of every goal on
 *    minute 90 against the 1.1% a flat draw gives it, because a straight line
 *    has no way to know the 45th minute proper is over in seconds.
 *
 * IT IS THE SAME SHAPE THROUGHOUT the competition: across the six editions a
 * permutation test gives p = 0.18, and group stage against knockout
 * p = 0.76. Cagier knockout football scoring later was the obvious risk
 * and it is not there.
 *
 * FIT QUALITY is read per band, not per minute: r2 against the 90 individual
 * minutes is only 0.13, because a single minute holds about 11 goals and is
 * mostly Poisson noise. What the model has to get right is the shape, and
 * across the six fifteen-minute bands its worst error is 1.0 points.
 *
 * THE ONE ASSUMPTION LEFT is that club football shares the shape. No club
 * season in the database records a minute, so nothing here can test it --
 * but it is a smaller leap than the flat draw it replaces.
 *
 * ADDED TIME IS CARRIED, not rounded away. A goal drawn on minute 90 is in
 * stoppage 89% of the time and on 45 84% of the time, with the added
 * minute drawn from the real spread, so the app can print 90+4' instead of
 * printing every late goal as a second 90'.
 *
 * GOALS ALSO REPEL EACH OTHER: 2 minutes apart at the least. Drawn
 * independently they shared a minute in 1.1% of pairs, which has never once
 * happened in the 1,481 real pairs, and 5.2% landed within two minutes
 * against a real 1.8%. Consecutive real goals are a median sixteen
 * minutes apart.
 *
 * Bookings still draw uniformly and carry no added time: the scrape carries
 * goals only, and a card curve would be invention again.
 */
internal object GoalMinutes {

    /** Share of goals falling in each minute, 1 to 90. */
    private val WEIGHT = doubleArrayOf(
        0.007831, 0.007879, 0.007926, 0.007974, 0.008021, 0.008068,  // 1-6
        0.008116, 0.008163, 0.008211, 0.008258, 0.008305, 0.008353,  // 7-12
        0.008400, 0.008448, 0.008495, 0.008542, 0.008590, 0.008637,  // 13-18
        0.008685, 0.008732, 0.008779, 0.008827, 0.008874, 0.008922,  // 19-24
        0.008969, 0.009016, 0.009064, 0.009111, 0.009159, 0.009206,  // 25-30
        0.009253, 0.009301, 0.009348, 0.009396, 0.009443, 0.009490,  // 31-36
        0.009538, 0.009585, 0.009633, 0.009680, 0.009727, 0.009775,  // 37-42
        0.009822, 0.009870, 0.029520, 0.009964, 0.010012, 0.010059,  // 43-48
        0.010107, 0.010154, 0.010201, 0.010249, 0.010296, 0.010344,  // 49-54
        0.010391, 0.010438, 0.010486, 0.010533, 0.010581, 0.010628,  // 55-60
        0.010675, 0.010723, 0.010770, 0.010818, 0.010865, 0.010912,  // 61-66
        0.010960, 0.011007, 0.011055, 0.011102, 0.011149, 0.011197,  // 67-72
        0.011244, 0.011292, 0.011339, 0.011386, 0.011434, 0.011481,  // 73-78
        0.011528, 0.011576, 0.011623, 0.011671, 0.011718, 0.011765,  // 79-84
        0.011813, 0.011860, 0.011908, 0.011955, 0.012002, 0.097786,  // 85-90
    )

    /** Running totals, so a draw is one roll and a walk rather than a sum. */
    private val CUMULATIVE = DoubleArray(WEIGHT.size).also {
        var running = 0.0
        for (i in WEIGHT.indices) {
            running += WEIGHT[i]
            it[i] = running
        }
    }

    /** The added minutes really played through, at each whistle. */
    private val STOPPAGE_45 = intArrayOf(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 6, 6)
    private val STOPPAGE_90 = intArrayOf(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 10, 11, 11, 12, 13)

    /** How often a goal on that minute was actually in added time. */
    private const val STOPPAGE_CHANCE_45 = 0.8438
    private const val STOPPAGE_CHANCE_90 = 0.8868

    /**
     * The least two goals in one match may be apart, in minutes.
     *
     * Calibrated against the real rate of pairs within two minutes (1.8%):
     * no gap at all gives 5.2%, a one-minute gap 4.2%, and this gives 2.2%.
     */
    const val MIN_SEPARATION = 2

    /** Redraws before a goal is placed wherever it last landed. */
    private const val ATTEMPTS = 20

    /** A moment in a match: the minute on the scoresheet, and added time if any. */
    data class Moment(val minute: Int, val stoppage: Int?) {
        /** Minutes actually played when it happened — 90+4 is later than 90+1. */
        val played: Int get() = minute + (stoppage ?: 0)
    }

    /**
     * When the next goal of a match goes in.
     *
     * [from] is how a substitute is handled: the distribution is truncated to
     * the part of the match he was on the pitch for and renormalised, rather
     * than redrawn until it fits, so his goals keep the same late tilt as
     * everyone else's over the minutes he could have scored in.
     *
     * [taken] is every moment already given to EITHER side in this match, as
     * [Moment.played]. Football's goals do not land on top of each other and
     * independent draws do, so a candidate too close to one of these is drawn
     * again. After [ATTEMPTS] the last candidate stands: a ten-goal match still
     * leaves most of the ninety free, so that is a guard, not a path anyone
     * takes.
     */
    fun draw(random: Random, from: Int = 1, taken: List<Int> = emptyList()): Moment {
        var moment = candidate(random, from)
        repeat(ATTEMPTS) {
            if (taken.none { kotlin.math.abs(moment.played - it) < MIN_SEPARATION }) return moment
            moment = candidate(random, from)
        }
        return moment
    }

    private fun candidate(random: Random, from: Int): Moment {
        val minute = minute(random, from)
        val stoppage = when (minute) {
            45 -> STOPPAGE_45.takeIf { random.nextDouble() < STOPPAGE_CHANCE_45 }
            90 -> STOPPAGE_90.takeIf { random.nextDouble() < STOPPAGE_CHANCE_90 }
            else -> null
        }
        return Moment(minute, stoppage?.let { it[random.nextInt(it.size)] })
    }

    private fun minute(random: Random, from: Int): Int {
        val lo = from.coerceIn(1, 90)
        val below = if (lo == 1) 0.0 else CUMULATIVE[lo - 2]
        val span = CUMULATIVE[89] - below
        val roll = below + random.nextDouble() * span
        for (i in lo - 1..89) {
            if (roll <= CUMULATIVE[i]) return i + 1
        }
        return 90
    }
}
