package com.dreamxi.app.sim

import kotlin.random.Random

/** A side in a league season: who they are, and how good they are. */
data class SimTeam(
    val id: String,
    val name: String,
    val season: String,
    val rating: TeamRating,
    /** True for the user's drafted XI, so the UI can pick it out of the table. */
    val isUserTeam: Boolean = false,
    /** The eleven the rating was computed from. */
    val xi: List<SimSlot> = emptyList(),
    /**
     * Who gets credited when this side scores. For a real club this is the
     * whole squad weighted by what they actually did; for the user's XI it is
     * the eleven. See [SquadProfile].
     */
    val squad: SquadProfile = SquadProfile.EMPTY,
)

/** One fixture, once played. */
data class SimFixture(
    val matchday: Int,
    val home: SimTeam,
    val away: SimTeam,
    val result: MatchResult,
    /** Scorers, assists and bookings. Empty when no squad was supplied. */
    val events: MatchEvents = MatchEvents(),
    /**
     * False when the scoreline is a real historical result rather than one the
     * engine produced. In a counterfactual season only the user's own 38
     * matches are simulated; the other 342 actually happened.
     */
    val simulated: Boolean = true,
) {
    /** The other side, from [team]'s point of view. Null if not involved. */
    fun opponentOf(team: SimTeam): SimTeam? = when (team.id) {
        home.id -> away
        away.id -> home
        else -> null
    }

    fun goalsFor(team: SimTeam): Int? = when (team.id) {
        home.id -> result.homeGoals
        away.id -> result.awayGoals
        else -> null
    }

    fun goalsAgainst(team: SimTeam): Int? = when (team.id) {
        home.id -> result.awayGoals
        away.id -> result.homeGoals
        else -> null
    }

    fun pointsFor(team: SimTeam): Int? = when (team.id) {
        home.id -> result.homePoints
        away.id -> result.awayPoints
        else -> null
    }
}

/** A team's line in the final table. */
data class TableRow(
    val position: Int,
    val team: SimTeam,
    val played: Int,
    val won: Int,
    val drawn: Int,
    val lost: Int,
    val goalsFor: Int,
    val goalsAgainst: Int,
    val points: Int,
) {
    val goalDifference: Int get() = goalsFor - goalsAgainst
}

/** One real historical result, as loaded from the fixtures table. */
data class RealFixture(
    val matchday: Int,
    val homeTeamId: String,
    val awayTeamId: String,
    val homeGoals: Int,
    val awayGoals: Int,
)

/** A completed season: every fixture, and the table they produced. */
data class SeasonResult(
    val table: List<TableRow>,
    val fixtures: List<SimFixture>,
    val seed: Long,
) {
    fun rowFor(team: SimTeam): TableRow? = table.firstOrNull { it.team.id == team.id }
    val userRow: TableRow? get() = table.firstOrNull { it.team.isUserTeam }

    /** This team's matches in matchday order. */
    fun fixturesFor(team: SimTeam): List<SimFixture> =
        fixtures.filter { it.home.id == team.id || it.away.id == team.id }
}

/**
 * Keeps match results and match REPORTS on separate random streams.
 *
 * They used to share one generator, which quietly coupled two unrelated things:
 * changing how a goal's minute is drawn consumed a different number of random
 * numbers, which shifted every subsequent scoreline and reshuffled entire league
 * tables. A season's results must depend on the squads and the seed, and on
 * nothing about how the scoresheet is written up.
 */
private const val EVENT_STREAM_OFFSET = 0x5EED_1234L

/**
 * Plays a full league season: every side home and away against every other,
 * then sorts the table the way football does.
 *
 * The fixture list is generated by the circle method, which is how real
 * fixture lists are built — it guarantees each team plays exactly once per
 * matchday, which a naive shuffle of all pairings does not. That matters
 * because the user watches this unfold as a season, not as a bag of results:
 * a schedule where a side plays three times in week one and not at all in week
 * two would read as broken even though the final table would be identical.
 *
 * The whole season is driven by one seed, so a run can be reproduced exactly.
 */
object SeasonSimulator {

    fun play(teams: List<SimTeam>, seed: Long): SeasonResult {
        require(teams.size >= 2) { "a season needs at least two teams" }
        require(teams.map { it.id }.toSet().size == teams.size) { "duplicate team ids" }

        // Scrambled for the same reason as the takeover draw: consecutive
        // run ids must not produce correlated seasons. See mixSeed.
        val random = Random(mixSeed(seed))
        val eventRandom = Random(mixSeed(seed + EVENT_STREAM_OFFSET))
        // One assist budget per club for the whole season — the same reason as
        // in playCounterfactual: drawing an assister afresh for every goal is
        // far wider than football, and produced top providers beyond anything a
        // real season has recorded. See SquadProfile.assistBudget.
        //
        // Every side here is a built XI rather than a real club, so every budget
        // is an estimate and gets scaled to the goals the side is expected to
        // score. Unscaled, a 25-credit budget had to cover 40-odd goals and the
        // league's assisted share fell to 58.5% against a real 70.4%.
        val assistLedgers = teams.associate {
            it.id to it.squad.newAssistLedger(it.rating.attack * SimModel.MATCHES_PER_SEASON)
        }
        val goalLedgers = teams.associate {
            it.id to it.squad.newGoalLedger(it.rating.attack * SimModel.MATCHES_PER_SEASON)
        }
        val fixtures = schedule(teams).map { (matchday, pair) ->
            val (home, away) = pair
            val result = MatchEngine.play(home.rating, away.rating, random)
            SimFixture(
                matchday = matchday,
                home = home,
                away = away,
                result = result,
                // A separate stream from the scoreline, so changing how a
                // report is written can never move a result.
                events = MatchReporter.report(
                    home.id, home.squad, away.id, away.squad, result, eventRandom,
                    homeAssists = assistLedgers[home.id],
                    awayAssists = assistLedgers[away.id],
                    homeGoalsLedger = goalLedgers[home.id],
                    awayGoalsLedger = goalLedgers[away.id],
                ),
            )
        }
        return SeasonResult(buildTable(teams, fixtures), fixtures, seed)
    }

    /**
     * Plays a season the way a counterfactual should be played: the user's XI
     * takes a relegated club's place, and NOTHING ELSE ABOUT HISTORY CHANGES.
     *
     * WHY THIS REPLACED A FULL SIMULATION. Re-simulating all 380 matches meant
     * re-deciding the whole league, so Barcelona could win 2021/22 when Real
     * Madrid actually did. The user is not asking "what if this season were
     * replayed?" — they are asking "could my eleven have done it?", and that
     * question is only meaningful against the season that really happened.
     *
     * HOW IT WORKS. The replaced club's 38 real fixtures are handed to the
     * user's XI — same matchdays, same venues, same opponents, so the calendar
     * is a real fixture list rather than a generated one. Those 38 are played
     * by the engine. The other 342 keep their real scorelines untouched.
     *
     * The table therefore reconciles exactly: every club's record is its real
     * one except for the two matches it played against the user instead of
     * against the club that went down. A side that took six points off that
     * club and none off the user drops further than one place, and one that
     * lost to them but beats the user climbs. That is more faithful than
     * shifting everyone down a row, and it means the user's season genuinely
     * moves the league rather than being slotted into a frozen one.
     *
     * Scorers are attributed for the real matches too, from each club's actual
     * squad, so the top-scorer list covers the whole league and lands on the
     * players who really scored those goals.
     */
    fun playCounterfactual(
        real: List<RealFixture>,
        teams: List<SimTeam>,
        user: SimTeam,
        replacedTeamId: String,
        seed: Long,
    ): SeasonResult {
        val byId = teams.associateBy { it.id } + (user.id to user)
        val random = Random(mixSeed(seed))
        val eventRandom = Random(mixSeed(seed + EVENT_STREAM_OFFSET))
        // One assist budget per club for the whole season, spent as goals are
        // reported. For the 342 real matches this deals out what the players
        // actually did; drawing an assister afresh for every goal produced top
        // providers no real season has ever seen.
        // Only the user's XI is an estimate. Every other club's budget is what
        // its players actually did, and 342 of these 380 matches really
        // happened — scaling those would replace a fact with a guess.
        fun expectedFor(id: String, team: SimTeam): Double? =
            if (id == user.id) team.rating.attack * SimModel.MATCHES_PER_SEASON else null
        val assistLedgers = byId.mapValues { (id, team) ->
            team.squad.newAssistLedger(expectedFor(id, team))
        }
        val goalLedgers = byId.mapValues { (id, team) ->
            team.squad.newGoalLedger(expectedFor(id, team))
        }

        val fixtures = real.mapNotNull { f ->
            // The replaced club's matches become the user's, keeping the
            // matchday and the venue.
            val homeId = if (f.homeTeamId == replacedTeamId) user.id else f.homeTeamId
            val awayId = if (f.awayTeamId == replacedTeamId) user.id else f.awayTeamId
            val home = byId[homeId] ?: return@mapNotNull null
            val away = byId[awayId] ?: return@mapNotNull null

            val involvesUser = home.id == user.id || away.id == user.id
            val result = if (involvesUser) {
                MatchEngine.play(home.rating, away.rating, random)
            } else {
                MatchResult(
                    homeGoals = f.homeGoals,
                    awayGoals = f.awayGoals,
                    homeExpected = f.homeGoals.toDouble(),
                    awayExpected = f.awayGoals.toDouble(),
                )
            }
            SimFixture(
                matchday = f.matchday,
                home = home,
                away = away,
                result = result,
                events = MatchReporter.report(
                    home.id, home.squad, away.id, away.squad, result, eventRandom,
                    homeAssists = assistLedgers[home.id],
                    awayAssists = assistLedgers[away.id],
                    homeGoalsLedger = goalLedgers[home.id],
                    awayGoalsLedger = goalLedgers[away.id],
                ),
                simulated = involvesUser,
            )
        }

        val playing = teams.filterNot { it.id == replacedTeamId } + user
        return SeasonResult(buildTable(playing, fixtures), fixtures, seed)
    }

    /**
     * Round-robin by the circle method: one team is pinned and the rest rotate
     * around it. With an odd number of teams a bye is added so the rotation
     * still works, and its matches are dropped — which is what lets a season
     * run even when a league-season loaded fewer clubs than it really had.
     *
     * The second half of the season repeats the first with the venues
     * reversed, so every pairing happens exactly twice: once at each ground.
     */
    private fun schedule(teams: List<SimTeam>): List<Pair<Int, Pair<SimTeam, SimTeam>>> {
        val rotation = teams.toMutableList<SimTeam?>()
        // The bye. Whoever is drawn against it that round sits the week out.
        if (rotation.size % 2 == 1) rotation.add(null)

        val n = rotation.size
        val roundsPerHalf = n - 1
        val out = mutableListOf<Pair<Int, Pair<SimTeam, SimTeam>>>()

        for (round in 0 until roundsPerHalf) {
            for (i in 0 until n / 2) {
                val a = rotation[i]
                val b = rotation[n - 1 - i]
                if (a == null || b == null) continue
                // Alternate venues round to round, otherwise the pinned team
                // would play every first-half fixture at home.
                val (home, away) = if ((round + i) % 2 == 0) a to b else b to a
                out += (round + 1) to (home to away)
                // The reverse fixture, in the mirrored half of the season.
                out += (round + 1 + roundsPerHalf) to (away to home)
            }
            // Rotate everything but the first entry.
            val moving = rotation.removeAt(n - 1)
            rotation.add(1, moving)
        }
        return out.sortedBy { it.first }
    }

    /**
     * The table. Sorted by points, then goal difference, then goals scored —
     * the Premier League's order, and La Liga's too once head-to-head is set
     * aside. Ties beyond that fall back to name so the order is stable rather
     * than dependent on iteration order.
     */
    fun buildTable(teams: List<SimTeam>, fixtures: List<SimFixture>): List<TableRow> {
        data class Acc(
            var p: Int = 0, var w: Int = 0, var d: Int = 0, var l: Int = 0,
            var gf: Int = 0, var ga: Int = 0, var pts: Int = 0,
        )

        val acc = teams.associate { it.id to Acc() }
        for (f in fixtures) {
            for (team in listOf(f.home, f.away)) {
                val a = acc[team.id] ?: continue
                val gf = f.goalsFor(team) ?: continue
                val ga = f.goalsAgainst(team) ?: continue
                val pts = f.pointsFor(team) ?: continue
                a.p++; a.gf += gf; a.ga += ga; a.pts += pts
                when {
                    gf > ga -> a.w++
                    gf == ga -> a.d++
                    else -> a.l++
                }
            }
        }

        return teams
            .map { it to acc.getValue(it.id) }
            .sortedWith(
                compareByDescending<Pair<SimTeam, Acc>> { it.second.pts }
                    .thenByDescending { it.second.gf - it.second.ga }
                    .thenByDescending { it.second.gf }
                    .thenBy { it.first.name },
            )
            .mapIndexed { index, (team, a) ->
                TableRow(index + 1, team, a.p, a.w, a.d, a.l, a.gf, a.ga, a.pts)
            }
    }
}
