package com.dreamxi.app.sim

// GENERATED by etl/wing_back_cost.py from EA's lwb/rwb columns. Do not edit by hand.

/**
 * What a wing-back slot costs a player, against his full-back rating.
 *
 * The stored grid has ONE full-back column, max(lb, rb), because EA's left
 * and right columns are identical for every player in the file. Its `lwb` and
 * `rwb` columns are not, and a 3-5-2 is two wing-backs — so every wing-back
 * in the app was priced as a full-back. Mascherano is the case that surfaced
 * it: EA gives him 82 at full-back and 80 at wing-back, and the app was
 * offering the 82.
 *
 * The gap depends on the player's role and almost nothing else, because a
 * wing-back is simply further up the pitch: a centre-back loses two points
 * going there, a forward gains two, a full-back is one already. Measured
 * across 159,996 player-editions of EA's own ratings.
 *
 * IT IS AN AVERAGE, not the player's own number — that would need a stored
 * pos_rating_wb, a migration and a reload of every season. Within-role spread
 * is about a point (sd 0.86 to 1.35), so this is worth roughly that much.
 */
internal val WingBackCost: Map<String, Int> = mapOf(
    "CB" to 2,  // n=30861, mean +2.04, sd 1.20
    "FB" to 0,  // n=28074, mean -0.05, sd 0.86
    "DM" to 0,  // n=14475, mean -0.02, sd 0.89
    "CM" to -1,  // n=21128, mean -1.03, sd 1.01
    "CAM" to -3,  // n=10950, mean -2.53, sd 1.35
    "Winger" to -3,  // n=27738, mean -2.66, sd 1.32
    "ST" to -2,  // n=26770, mean -2.02, sd 1.04
)
