"""
Downloads a flag for every nation World Cup mode shows, and generates the app's
name -> flag lookup from the same table.

    python wc_flags.py

WRITES
  app/src/main/res/drawable-nodpi/flag_<code>.png   320px wide, one per country
  app/src/main/java/com/dreamxi/app/core/ui/NationFlags.kt

WHY ONE TABLE. The app shows nations under the fixture sources' spellings —
"Czechia" in 2026 and "Czech Republic" in 2006, "USA" and "United States",
"Bosnia–Herz" and "Bosnia Herzegovina" — and every one of those has to land on
the same flag. Keeping the mapping here and GENERATING the Kotlin from it means a
name added to one cannot be missing from the other.

SOURCES. flagcdn.com serves every current flag by ISO 3166 code as PNG, public
domain, including the home nations (gb-eng, gb-sct, gb-wls). Serbia and
Montenegro, which played in 2006, dissolved that year and has no current code,
so its flag comes from Wikimedia Commons (public domain).

CHECKED before the Kotlin is written: every nation in the exported fixtures has
a code, and every file is a real PNG — a CDN error page saved as flag_xx.png
would compile and draw nothing.
"""
from __future__ import annotations

import struct
import sys
import time
from pathlib import Path

import requests

HERE = Path(__file__).parent
APP = HERE.parent / "app" / "src"
DRAWABLE = APP / "main" / "res" / "drawable-nodpi"
KOTLIN = APP / "main" / "java" / "com" / "dreamxi" / "app" / "core" / "ui" / "NationFlags.kt"
ENTRIES = APP / "test" / "resources" / "wc" / "entries.tsv"
USER_AGENT = "ERA-XI-flags/1.0 (kunal1lele@gmail.com)"

#: Display name, exactly as the app shows it -> ISO 3166 code (flagcdn's key).
FLAG_CODES = {
    "Algeria": "dz", "Angola": "ao", "Argentina": "ar", "Australia": "au", "Austria": "at",
    "Belgium": "be", "Bosnia Herzegovina": "ba", "Bosnia–Herz": "ba", "Brazil": "br",
    "Cabo Verde": "cv", "Cameroon": "cm", "Canada": "ca", "Chile": "cl", "Colombia": "co",
    "Congo DR": "cd", "Costa Rica": "cr", "Croatia": "hr", "Curaçao": "cw",
    "Czech Republic": "cz", "Czechia": "cz", "Côte d'Ivoire": "ci", "Denmark": "dk",
    "Ecuador": "ec", "Egypt": "eg", "England": "gb-eng", "France": "fr", "Germany": "de",
    "Ghana": "gh", "Greece": "gr", "Haiti": "ht", "Honduras": "hn", "IR Iran": "ir",
    "Iceland": "is", "Iraq": "iq", "Italy": "it", "Japan": "jp", "Jordan": "jo",
    "Korea DPR": "kp", "Korea Republic": "kr", "Mexico": "mx", "Morocco": "ma",
    "Netherlands": "nl", "New Zealand": "nz", "Nigeria": "ng", "Norway": "no", "Panama": "pa",
    "Paraguay": "py", "Peru": "pe", "Poland": "pl", "Portugal": "pt", "Qatar": "qa",
    "Russia": "ru", "Saudi Arabia": "sa", "Scotland": "gb-sct", "Senegal": "sn",
    "Serbia": "rs", "Serbia & Montenegro": "scg", "Slovakia": "sk", "Slovenia": "si",
    "South Africa": "za", "Spain": "es", "Sweden": "se", "Switzerland": "ch", "Togo": "tg",
    "Trinidad Tobago": "tt", "Tunisia": "tn", "Türkiye": "tr", "USA": "us",
    "Ukraine": "ua", "United States": "us", "Uruguay": "uy", "Uzbekistan": "uz",
    "Wales": "gb-wls",
}

#: Flags with no current ISO code, from Wikimedia Commons.
SPECIAL_URLS = {
    "scg": "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_Serbia_and_Montenegro.svg?width=320",
}


def resource_name(code: str) -> str:
    return "flag_" + code.replace("-", "_")


def png_size(data: bytes) -> tuple[int, int] | None:
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", data[16:24])


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    shown = {line.split("\t")[1] for line in ENTRIES.read_text(encoding="utf-8").splitlines()[1:] if line}
    missing = sorted(shown - FLAG_CODES.keys())
    if missing:
        raise SystemExit(f"no flag code for: {missing}")

    DRAWABLE.mkdir(parents=True, exist_ok=True)
    session = requests.Session()
    session.headers["User-Agent"] = USER_AGENT
    problems = []
    for code in sorted(set(FLAG_CODES.values())):
        path = DRAWABLE / f"{resource_name(code)}.png"
        if path.exists() and png_size(path.read_bytes()):
            continue
        url = SPECIAL_URLS.get(code, f"https://flagcdn.com/w320/{code}.png")
        resp = session.get(url, timeout=60, allow_redirects=True)
        size = png_size(resp.content) if resp.ok else None
        if size is None:
            problems.append(f"{code}: {resp.status_code} from {url} was not a PNG")
            continue
        path.write_bytes(resp.content)
        print(f"  {path.name:22s} {size[0]}x{size[1]}  {len(resp.content):6d} bytes")
        time.sleep(0.2)
    if problems:
        raise SystemExit("\n".join(problems))

    lines = [
        "package com.dreamxi.app.core.ui",
        "",
        "import com.dreamxi.app.R",
        "",
        "// GENERATED by etl/wc_flags.py. Do not edit by hand: add a name there and rerun.",
        "",
        "/**",
        " * A nation's flag, by the name the app shows it under. Several spellings map",
        " * to one flag because the fixture sources spell nations differently across",
        " * editions (\"Czechia\" 2026, \"Czech Republic\" 2006).",
        " */",
        "internal val NationFlags: Map<String, Int> = mapOf(",
    ]
    for name in sorted(FLAG_CODES):
        escaped = name.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        lines.append(f'    "{escaped}" to R.drawable.{resource_name(FLAG_CODES[name])},')
    lines += [")", ""]
    KOTLIN.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n{len(set(FLAG_CODES.values()))} flags for {len(FLAG_CODES)} names; wrote {KOTLIN.name}")


if __name__ == "__main__":
    main()
