"""What EA thinks a player is worth at WING-back rather than full-back.

WHY THIS EXISTS. The stored grid has one full-back column, built as
max(lb, rb) — deliberately, because EA's lb and rb columns are identical for
every player in the file, so keeping both would imply a left/right distinction
the source does not make (see fifa_ratings.SLOT_COLUMNS).

EA's `lwb` and `rwb` columns are NOT identical to those, and the app throws
them away. Every 3-5-2, 5-3-2 and 5-4-1 has two wing-back slots, and each one
was being priced off the full-back number. The reported case was Mascherano at
left wing-back: EA FIFA 15 has him at lb 82 / rb 82 but lwb 80 / rwb 80, so the
app offered him two points more than EA ever gave him there.

WHY A PER-ROLE OFFSET RATHER THAN A NEW COLUMN. The exact fix is a stored
pos_rating_wb beside the other seven, which needs a migration and a reload of
every season. The gap turns out to be strongly predictable from the player's
role and nothing else -- a wing-back is further up the pitch, so defenders lose
and attackers gain -- and measuring it across 160,000 player-editions gives a
table good to about a point. That buys most of the accuracy for none of the
migration, and the column stays available if the residual ever matters.

    role     mean gap   sd    what it means
    CB         +2.0    1.20   a centre-back is WORSE pushed up the wing
    FB         -0.1    0.86   a full-back is a wing-back already
    DM         -0.0    0.89   likewise
    CM         -1.0    1.01
    ST         -2.0    1.04   a forward is BETTER further up than at the back
    CAM        -2.5    1.35
    Winger     -2.7    1.32
"""
from __future__ import annotations

import collections
import csv
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).parent
ARCHIVE = HERE / "archive" / "male_players.csv"
KOTLIN = HERE.parent / "app/src/main/java/com/dreamxi/app/sim/WingBackCost.kt"

#: EA's primary position to the role buckets the app stores.
EA_ROLE = {
    "CB": "CB", "LB": "FB", "RB": "FB", "LWB": "FB", "RWB": "FB",
    "CDM": "DM", "CM": "CM", "CAM": "CAM",
    "LM": "Winger", "RM": "Winger", "LW": "Winger", "RW": "Winger",
    "ST": "ST", "CF": "ST",
}
ROLES = ["CB", "FB", "DM", "CM", "CAM", "Winger", "ST"]


def base(value: str | None) -> int | None:
    """EA writes "82+1" for a player on form; the base number is the rating."""
    match = re.match(r"^\s*(\d+)", value or "")
    return int(match.group(1)) if match else None


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    if not ARCHIVE.exists():
        raise SystemExit(f"{ARCHIVE} is missing — this needs the EA archive to measure anything")

    csv.field_size_limit(10 ** 7)
    gaps: dict[str, list[int]] = collections.defaultdict(list)
    with ARCHIVE.open(encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            lb, rb = base(row.get("lb")), base(row.get("rb"))
            lwb, rwb = base(row.get("lwb")), base(row.get("rwb"))
            if None in (lb, rb, lwb, rwb):
                continue
            position = (row.get("player_positions") or "").split(",")[0].strip()
            role = EA_ROLE.get(position)
            if role is None:
                continue
            # The same max() the stored columns use, so the offset applies to
            # exactly the number the app holds.
            gaps[role].append(max(lb, rb) - max(lwb, rwb))

    print(f"{'role':8s} {'n':>7s} {'mean':>6s} {'sd':>5s}  {'within +/-1':>11s}")
    table: dict[str, int] = {}
    for role in ROLES:
        values = gaps[role]
        mean = statistics.mean(values)
        sd = statistics.pstdev(values)
        close = sum(1 for v in values if abs(v - mean) <= 1) / len(values) * 100
        table[role] = round(mean)
        print(f"{role:8s} {len(values):7d} {mean:6.2f} {sd:5.2f}  {close:10.1f}%")

    lines = [
        "package com.dreamxi.app.sim",
        "",
        "// GENERATED by etl/wing_back_cost.py from EA's lwb/rwb columns. Do not edit by hand.",
        "",
        "/**",
        " * What a wing-back slot costs a player, against his full-back rating.",
        " *",
        " * The stored grid has ONE full-back column, max(lb, rb), because EA's left",
        " * and right columns are identical for every player in the file. Its `lwb` and",
        " * `rwb` columns are not, and a 3-5-2 is two wing-backs — so every wing-back",
        " * in the app was priced as a full-back. Mascherano is the case that surfaced",
        " * it: EA gives him 82 at full-back and 80 at wing-back, and the app was",
        " * offering the 82.",
        " *",
        " * The gap depends on the player's role and almost nothing else, because a",
        " * wing-back is simply further up the pitch: a centre-back loses two points",
        " * going there, a forward gains two, a full-back is one already. Measured",
        f" * across {sum(len(v) for v in gaps.values()):,} player-editions of EA's own ratings.",
        " *",
        " * IT IS AN AVERAGE, not the player's own number — that would need a stored",
        " * pos_rating_wb, a migration and a reload of every season. Within-role spread",
        " * is about a point (sd 0.86 to 1.35), so this is worth roughly that much.",
        " */",
        "internal val WingBackCost: Map<String, Int> = mapOf(",
    ]
    for role in ROLES:
        values = gaps[role]
        lines.append(
            f'    "{role}" to {table[role]},'
            f"  // n={len(values)}, mean {statistics.mean(values):+.2f}, sd {statistics.pstdev(values):.2f}"
        )
    lines += [
        ")",
        "",
    ]
    KOTLIN.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote {KOTLIN.name}")


if __name__ == "__main__":
    main()
