package com.dreamxi.app.sim.worldcup

import kotlin.math.exp

// GENERATED by etl/wc_output.py from the real club seasons. Do not edit by hand.

/**
 * What a World Cup player of a given rating produces, per position.
 *
 * A World Cup squad has ratings and positions and no stats, so output has to
 * be estimated from rating. It grows MULTIPLICATIVELY:
 *
 *     rate = base * exp(slope * (rating - the role's median rating))
 *
 * fitted per role on per-band means of real club seasons (900+ minutes).
 * The club engine's linear 3%-per-point fallback, which this replaces HERE
 * AND ONLY HERE, flattered weak attackers and halved elite ones: it put a
 * 92-rated winger at 0.28 npxG/90 against a measured 0.57, so a side of 92s
 * rated no better in attack than a real England XI.
 *
 * CLUB MODE IS UNCHANGED. Club players have their own per-season xG; this is
 * used by NationalSide.simPlayer alone.
 */
internal object WcOutput {

    /** [top] is the highest rating the fit saw: above it the curve holds flat. */
    private data class Curve(val base: Double, val slope: Double, val anchor: Int, val top: Int)

    private val NPXG90: Map<String, Curve> = mapOf(
        "GK" to Curve(0.00010, -0.14228, 79, 87),  // n=510, r2=0.05, measured to 87
        "CB" to Curve(0.04454, 0.03499, 77, 89),  // n=1322, r2=0.78, measured to 89
        "FB" to Curve(0.03508, 0.05303, 77, 87),  // n=1154, r2=0.84, measured to 87
        "DM" to Curve(0.05223, 0.07979, 77, 85),  // n=566, r2=0.86, measured to 85
        "CM" to Curve(0.08011, 0.08405, 77, 89),  // n=816, r2=0.88, measured to 89
        "CAM" to Curve(0.17861, 0.05438, 80, 89),  // n=360, r2=0.91, measured to 89
        "Winger" to Curve(0.16136, 0.07702, 78, 95),  // n=1031, r2=0.97, measured to 95
        "ST" to Curve(0.30454, 0.07273, 79, 91),  // n=914, r2=0.99, measured to 91
    )

    private val GOALS90: Map<String, Curve> = mapOf(
        "GK" to Curve(0.00151, -0.27285, 79, 83),  // n=510, r2=0.68, measured to 83
        "CB" to Curve(0.04082, 0.04739, 77, 89),  // n=1322, r2=0.83, measured to 89
        "FB" to Curve(0.02814, 0.07694, 77, 87),  // n=1154, r2=0.78, measured to 87
        "DM" to Curve(0.04424, 0.13370, 77, 85),  // n=566, r2=0.86, measured to 85
        "CM" to Curve(0.07014, 0.12814, 77, 89),  // n=816, r2=0.92, measured to 89
        "CAM" to Curve(0.17573, 0.07969, 80, 89),  // n=360, r2=0.84, measured to 89
        "Winger" to Curve(0.14697, 0.12044, 78, 95),  // n=1031, r2=0.99, measured to 95
        "ST" to Curve(0.30453, 0.11107, 79, 91),  // n=914, r2=0.94, measured to 91
    )

    private val ASSISTS90: Map<String, Curve> = mapOf(
        "GK" to Curve(0.00260, 0.03157, 79, 89),  // n=510, r2=0.06, measured to 89
        "CB" to Curve(0.01996, 0.02576, 77, 89),  // n=1322, r2=0.53, measured to 89
        "FB" to Curve(0.06118, 0.10021, 77, 87),  // n=1154, r2=0.93, measured to 87
        "DM" to Curve(0.03168, 0.20385, 77, 85),  // n=566, r2=0.92, measured to 85
        "CM" to Curve(0.06028, 0.17430, 77, 89),  // n=816, r2=0.87, measured to 89
        "CAM" to Curve(0.15221, 0.11784, 80, 89),  // n=360, r2=0.93, measured to 89
        "Winger" to Curve(0.14024, 0.09647, 78, 95),  // n=1031, r2=0.94, measured to 95
        "ST" to Curve(0.10931, 0.08135, 79, 91),  // n=914, r2=0.96, measured to 91
    )

    private fun rate(curves: Map<String, Curve>, role: String, rating: Double): Double {
        val curve = curves[role] ?: return 0.0
        // Held flat above the highest rating the fit saw: beyond that the curve
        // would be extrapolating, and a 92-rated defensive midfielder is exactly
        // where that goes wrong.
        val measured = rating.coerceAtMost(curve.top.toDouble())
        return curve.base * exp(curve.slope * (measured - curve.anchor))
    }

    /** Non-penalty expected goals per 90 — what the side's scoring is built from. */
    fun npxg90(role: String, rating: Double): Double = rate(NPXG90, role, rating)

    /** Goals per 90, penalties included: who gets credited once a goal is scored. */
    fun goals90(role: String, rating: Double): Double = rate(GOALS90, role, rating)

    /** Assists per 90, for the same job. */
    fun assists90(role: String, rating: Double): Double = rate(ASSISTS90, role, rating)
}
