package com.dreamxi.app.sim.worldcup

// GENERATED by etl/wc_calibration.py (section 4). Do not edit by hand: rerun it.

/**
 * The FALLBACK cost of playing out of position, for World Cup players with no
 * EA positional grid in any edition (13% of squad players, mostly FIFA 07
 * players who retired before FIFA 15). Everyone else is priced off his own
 * grid. Medians over FIFA 15-24 grids, by rating band, because the cost grows
 * with quality; a band cell with fewer than 30 players uses the all-ratings median.
 */
internal object WcPositionCosts {
    /** Lower bound of each band, on the modern rating scale. */
    val BAND_FLOORS: List<Int> = listOf(0, 75, 80, 85)

    /** Per band: "FROM>TO" -> rating change for a player who does NOT list TO. */
    val UNLISTED: List<Map<String, Int>> = listOf(
        mapOf("CB>FB" to -5, "CB>DM" to -5, "CB>CM" to -14, "CB>CAM" to -18, "CB>Winger" to -19, "CB>ST" to -17, "FB>CB" to -2, "FB>DM" to -3, "FB>CM" to -6, "FB>CAM" to -7, "FB>Winger" to -6, "FB>ST" to -9, "DM>CB" to -1, "DM>FB" to -2, "DM>CM" to -3, "DM>CAM" to -5, "DM>Winger" to -6, "DM>ST" to -8, "CM>CB" to -5, "CM>FB" to -3, "CM>DM" to -2, "CM>CAM" to -1, "CM>Winger" to -2, "CM>ST" to -4, "CAM>CB" to -17, "CAM>FB" to -12, "CAM>DM" to -12, "CAM>CM" to -4, "CAM>Winger" to 0, "CAM>ST" to -4, "Winger>CB" to -21, "Winger>FB" to -15, "Winger>DM" to -15, "Winger>CM" to -7, "Winger>CAM" to -2, "Winger>ST" to -4, "ST>CB" to -22, "ST>FB" to -20, "ST>DM" to -20, "ST>CM" to -10, "ST>CAM" to -4, "ST>Winger" to -3),
        mapOf("CB>FB" to -6, "CB>DM" to -5, "CB>CM" to -15, "CB>CAM" to -20, "CB>Winger" to -22, "CB>ST" to -20, "FB>CB" to -2, "FB>DM" to -2, "FB>CM" to -4, "FB>CAM" to -6, "FB>Winger" to -5, "FB>ST" to -9, "DM>CB" to -2, "DM>FB" to -3, "DM>CM" to -4, "DM>CAM" to -6, "DM>Winger" to -8, "DM>ST" to -9, "CM>CB" to -7, "CM>FB" to -5, "CM>DM" to -3, "CM>CAM" to -1, "CM>Winger" to -3, "CM>ST" to -6, "CAM>CB" to -23, "CAM>FB" to -17, "CAM>DM" to -15, "CAM>CM" to -4, "CAM>Winger" to -1, "CAM>ST" to -5, "Winger>CB" to -26, "Winger>FB" to -19, "Winger>DM" to -18, "Winger>CM" to -6, "Winger>CAM" to -1, "Winger>ST" to -4, "ST>CB" to -26, "ST>FB" to -24, "ST>DM" to -22, "ST>CM" to -9, "ST>CAM" to -4, "ST>Winger" to -4),
        mapOf("CB>FB" to -6, "CB>DM" to -4, "CB>CM" to -14, "CB>CAM" to -20, "CB>Winger" to -21, "CB>ST" to -20, "FB>CB" to -3, "FB>DM" to -2, "FB>CM" to -4, "FB>CAM" to -5, "FB>Winger" to -5, "FB>ST" to -8, "DM>CB" to -2, "DM>FB" to -3, "DM>CM" to -4, "DM>CAM" to -7, "DM>Winger" to -9, "DM>ST" to -10, "CM>CB" to -8, "CM>FB" to -6, "CM>DM" to -4, "CM>CAM" to -2, "CM>Winger" to -3, "CM>ST" to -6, "CAM>CB" to -25, "CAM>FB" to -18, "CAM>DM" to -15, "CAM>CM" to -4, "CAM>Winger" to -1, "CAM>ST" to -6, "Winger>CB" to -29, "Winger>FB" to -21, "Winger>DM" to -20, "Winger>CM" to -6, "Winger>CAM" to -1, "Winger>ST" to -5, "ST>CB" to -28, "ST>FB" to -25, "ST>DM" to -23, "ST>CM" to -9, "ST>CAM" to -3, "ST>Winger" to -3),
        mapOf("CB>FB" to -6, "CB>DM" to -4, "CB>CM" to -13, "CB>CAM" to -18, "CB>Winger" to -21, "CB>ST" to -19, "FB>CB" to -4, "FB>DM" to -2, "FB>CM" to -4, "FB>CAM" to -4, "FB>Winger" to -4, "FB>ST" to -8, "DM>CB" to -2, "DM>FB" to -4, "DM>CM" to -3, "DM>CAM" to -7, "DM>Winger" to -9, "DM>ST" to -10, "CM>CB" to -13, "CM>FB" to -9, "CM>DM" to -5, "CM>CAM" to -1, "CM>Winger" to -3, "CM>ST" to -8, "CAM>CB" to -29, "CAM>FB" to -21, "CAM>DM" to -17, "CAM>CM" to -5, "CAM>Winger" to -1, "CAM>ST" to -7, "Winger>CB" to -33, "Winger>FB" to -24, "Winger>DM" to -23, "Winger>CM" to -7, "Winger>CAM" to 0, "Winger>ST" to -5, "ST>CB" to -30, "ST>FB" to -26, "ST>DM" to -24, "ST>CM" to -9, "ST>CAM" to -2, "ST>Winger" to -3),
    )

    /** Per band: role -> rating change for a player who lists it as a secondary position. */
    val LISTED: List<Map<String, Int>> = listOf(
        mapOf("CB" to 0, "FB" to -2, "DM" to -1, "CM" to -2, "CAM" to 0, "Winger" to -1, "ST" to -2),
        mapOf("CB" to 0, "FB" to -3, "DM" to -1, "CM" to -2, "CAM" to 0, "Winger" to -1, "ST" to -3),
        mapOf("CB" to 0, "FB" to -3, "DM" to -2, "CM" to -2, "CAM" to 0, "Winger" to -1, "ST" to -4),
        mapOf("CB" to 0, "FB" to -3, "DM" to -3, "CM" to -2, "CAM" to 0, "Winger" to -1, "ST" to -3),
    )

    fun band(rating: Double): Int = BAND_FLOORS.indexOfLast { rating >= it }.coerceAtLeast(0)
}
